APP_NAME = "APS MIDI Prep Tool"
APP_VERSION = "0.5.3"
APP_TITLE_WITH_VERSION = f"{APP_NAME} v{APP_VERSION}"
APP_WEBSITE = "https://www.alexanderpeppe.com/"
UPDATE_CHECK_URL = "https://www.alexanderpeppe.com/aps-midi-prep-tool-data/update.json"

SETTINGS_ORG = "AlexPianoServiceLLC"
SETTINGS_APP = "APSMidiPrepTool"
LEGACY_SETTINGS_APP = "APSMidiTitleEditor"

COPYRIGHT_YEAR = "2026"
COPYRIGHT_HOLDER = "Alex's Piano Service LLC"
APP_AUTHOR = "Alexander Peppe"
APP_COMPANY = "Alex's Piano Service LLC"
APP_COMPANY_ADDRESS = "432 Elm St., Biddeford, ME 04005"
APP_LICENSE = "Apache License 2.0"
APP_COPYRIGHT_NOTICE = f"Copyright {COPYRIGHT_YEAR} {COPYRIGHT_HOLDER}"
